//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KolkoKrzyzyk.ServiceKolkoKrzyzyk {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceKolkoKrzyzyk.IGraKolkoKrzyzyk")]
    public interface IGraKolkoKrzyzyk {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraKolkoKrzyzyk/Start", ReplyAction="http://tempuri.org/IGraKolkoKrzyzyk/StartResponse")]
        void Start();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraKolkoKrzyzyk/Start", ReplyAction="http://tempuri.org/IGraKolkoKrzyzyk/StartResponse")]
        System.Threading.Tasks.Task StartAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraKolkoKrzyzyk/MakeMove", ReplyAction="http://tempuri.org/IGraKolkoKrzyzyk/MakeMoveResponse")]
        KolkoKrzyzyk.ServiceKolkoKrzyzyk.MakeMoveResponse MakeMove(KolkoKrzyzyk.ServiceKolkoKrzyzyk.MakeMoveRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraKolkoKrzyzyk/MakeMove", ReplyAction="http://tempuri.org/IGraKolkoKrzyzyk/MakeMoveResponse")]
        System.Threading.Tasks.Task<KolkoKrzyzyk.ServiceKolkoKrzyzyk.MakeMoveResponse> MakeMoveAsync(KolkoKrzyzyk.ServiceKolkoKrzyzyk.MakeMoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraKolkoKrzyzyk/CheckVictory", ReplyAction="http://tempuri.org/IGraKolkoKrzyzyk/CheckVictoryResponse")]
        int CheckVictory(int wiersz, int kolumna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraKolkoKrzyzyk/CheckVictory", ReplyAction="http://tempuri.org/IGraKolkoKrzyzyk/CheckVictoryResponse")]
        System.Threading.Tasks.Task<int> CheckVictoryAsync(int wiersz, int kolumna);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MakeMove", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MakeMoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int wiersz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int kolumna;
        
        public MakeMoveRequest() {
        }
        
        public MakeMoveRequest(int wiersz, int kolumna) {
            this.wiersz = wiersz;
            this.kolumna = kolumna;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MakeMoveResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MakeMoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool MakeMoveResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int wierszServer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int kolumnaServer;
        
        public MakeMoveResponse() {
        }
        
        public MakeMoveResponse(bool MakeMoveResult, int wierszServer, int kolumnaServer) {
            this.MakeMoveResult = MakeMoveResult;
            this.wierszServer = wierszServer;
            this.kolumnaServer = kolumnaServer;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGraKolkoKrzyzykChannel : KolkoKrzyzyk.ServiceKolkoKrzyzyk.IGraKolkoKrzyzyk, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GraKolkoKrzyzykClient : System.ServiceModel.ClientBase<KolkoKrzyzyk.ServiceKolkoKrzyzyk.IGraKolkoKrzyzyk>, KolkoKrzyzyk.ServiceKolkoKrzyzyk.IGraKolkoKrzyzyk {
        
        public GraKolkoKrzyzykClient() {
        }
        
        public GraKolkoKrzyzykClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GraKolkoKrzyzykClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GraKolkoKrzyzykClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GraKolkoKrzyzykClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Start() {
            base.Channel.Start();
        }
        
        public System.Threading.Tasks.Task StartAsync() {
            return base.Channel.StartAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KolkoKrzyzyk.ServiceKolkoKrzyzyk.MakeMoveResponse KolkoKrzyzyk.ServiceKolkoKrzyzyk.IGraKolkoKrzyzyk.MakeMove(KolkoKrzyzyk.ServiceKolkoKrzyzyk.MakeMoveRequest request) {
            return base.Channel.MakeMove(request);
        }
        
        public bool MakeMove(int wiersz, int kolumna, out int wierszServer, out int kolumnaServer) {
            KolkoKrzyzyk.ServiceKolkoKrzyzyk.MakeMoveRequest inValue = new KolkoKrzyzyk.ServiceKolkoKrzyzyk.MakeMoveRequest();
            inValue.wiersz = wiersz;
            inValue.kolumna = kolumna;
            KolkoKrzyzyk.ServiceKolkoKrzyzyk.MakeMoveResponse retVal = ((KolkoKrzyzyk.ServiceKolkoKrzyzyk.IGraKolkoKrzyzyk)(this)).MakeMove(inValue);
            wierszServer = retVal.wierszServer;
            kolumnaServer = retVal.kolumnaServer;
            return retVal.MakeMoveResult;
        }
        
        public System.Threading.Tasks.Task<KolkoKrzyzyk.ServiceKolkoKrzyzyk.MakeMoveResponse> MakeMoveAsync(KolkoKrzyzyk.ServiceKolkoKrzyzyk.MakeMoveRequest request) {
            return base.Channel.MakeMoveAsync(request);
        }
        
        public int CheckVictory(int wiersz, int kolumna) {
            return base.Channel.CheckVictory(wiersz, kolumna);
        }
        
        public System.Threading.Tasks.Task<int> CheckVictoryAsync(int wiersz, int kolumna) {
            return base.Channel.CheckVictoryAsync(wiersz, kolumna);
        }
    }
}
